export interface RealmOption {
  label: string;
  slug: string;
}

export const EU_REALMS: RealmOption[] = [
  { label: "Aegwynn", slug: "aegwynn" },
  { label: "Aerie Peak", slug: "aerie-peak" },
  { label: "Agamaggan", slug: "agamaggan" },
  { label: "Aggra (Português)", slug: "aggra" },
  { label: "Aggramar", slug: "aggramar" },
  { label: "Ahn'Qiraj", slug: "ahnqiraj" },
  { label: "Al'Akir", slug: "alakir" },
  { label: "Alexstrasza", slug: "alexstrasza" },
  { label: "Alonsus", slug: "alonsus" },
  { label: "Aman'Thul", slug: "amanthul" },
  { label: "Ambossar", slug: "ambossar" },
  { label: "Anachronos", slug: "anachronos" },
  { label: "Anetheron", slug: "anetheron" },
  { label: "Anub'arak", slug: "anubarak" },
  { label: "Anvilmar", slug: "anvilmar" },
  { label: "Arathor", slug: "arathor" },
  { label: "Argent Dawn", slug: "argent-dawn" },
  { label: "Arthas", slug: "arthas" },
  { label: "Arygos", slug: "arygos" },
  { label: "Aszune", slug: "aszune" },
  { label: "Auchindoun", slug: "auchindoun" },
  { label: "Azjol-Nerub", slug: "azjol-nerub" },
  { label: "Azshara", slug: "azshara" },
  { label: "Azuregos", slug: "azuregos" },
  { label: "Azuremyst", slug: "azuremyst" },
  { label: "Baelgun", slug: "baelgun" },
  { label: "Balnazzar", slug: "balnazzar" },
  { label: "Blackhand", slug: "blackhand" },
  { label: "Blackmoore", slug: "blackmoore" },
  { label: "Blackrock", slug: "blackrock" },
  { label: "Blackscar", slug: "blackscar" },
  { label: "Blade's Edge", slug: "blades-edge" },
  { label: "Bladefist", slug: "bladefist" },
  { label: "Bloodfeather", slug: "bloodfeather" },
  { label: "Bloodhoof", slug: "bloodhoof" },
  { label: "Bloodscalp", slug: "bloodscalp" },
  { label: "Boulderfist", slug: "boulderfist" },
  { label: "Bronze Dragonflight", slug: "bronze-dragonflight" },
  { label: "Bronzebeard", slug: "bronzebeard" },
  { label: "Burning Blade", slug: "burning-blade" },
  { label: "Burning Legion", slug: "burning-legion" },
  { label: "Burning Steppes", slug: "burning-steppes" },
  { label: "C'Thun", slug: "cthun" },
  { label: "Chamber of Aspects", slug: "chamber-of-aspects" },
  { label: "Chants éternels", slug: "chants-eternels" },
  { label: "Cho'gall", slug: "chogall" },
  { label: "Chromaggus", slug: "chromaggus" },
  { label: "Colinas Pardas", slug: "colinas-pardas" },
  { label: "Confrérie du Thorium", slug: "confrerie-du-thorium" },
  { label: "Conseil des Ombres", slug: "conseil-des-ombres" },
  { label: "Crushridge", slug: "crushridge" },
  { label: "Culte de la Rive noire", slug: "culte-de-la-rive-noire" },
  { label: "Daggerspine", slug: "daggerspine" },
  { label: "Darkmoon Faire", slug: "darkmoon-faire" },
  { label: "Darksorrow", slug: "darksorrow" },
  { label: "Darkspear", slug: "darkspear" },
  { label: "Das Konsortium", slug: "das-konsortium" },
  { label: "Das Syndikat", slug: "das-syndikat" },
  { label: "Deathwing", slug: "deathwing" },
  { label: "Defias Brotherhood", slug: "defias-brotherhood" },
  { label: "Dentarg", slug: "dentarg" },
  { label: "Der abyssische Rat", slug: "der-abyssische-rat" },
  { label: "Der Mithrilorden", slug: "der-mithrilorden" },
  { label: "Der Rat von Dalaran", slug: "der-rat-von-dalaran" },
  { label: "Destromath", slug: "destromath" },
  { label: "Dethecus", slug: "dethecus" },
  { label: "Die Aldor", slug: "die-aldor" },
  { label: "Die Arguswacht", slug: "die-arguswacht" },
  { label: "Die ewige Wacht", slug: "die-ewige-wacht" },
  { label: "Die Nachtwache", slug: "die-nachtwache" },
  { label: "Die Silberne Hand", slug: "die-silberne-hand" },
  { label: "Die Todeskrallen", slug: "die-todeskrallen" },
  { label: "Die Verbannten", slug: "die-verbannten" },
  { label: "Doomhammer", slug: "doomhammer" },
  { label: "Draenor", slug: "draenor" },
  { label: "Dragonblight", slug: "dragonblight" },
  { label: "Dragonmaw", slug: "dragonmaw" },
  { label: "Drak'thul", slug: "drakthul" },
  { label: "Drek'Thar", slug: "drekthar" },
  { label: "Dun Modr", slug: "dun-modr" },
  { label: "Dun Morogh", slug: "dun-morogh" },
  { label: "Dunemaul", slug: "dunemaul" },
  { label: "Durotan", slug: "durotan" },
  { label: "Earthen Ring", slug: "earthen-ring" },
  { label: "Echsenkessel", slug: "echsenkessel" },
  { label: "Eitrigg", slug: "eitrigg" },
  { label: "Eldre'Thalas", slug: "eldrethalas" },
  { label: "Emerald Dream", slug: "emerald-dream" },
  { label: "Emeriss", slug: "emeriss" },
  { label: "Eonar", slug: "eonar" },
  { label: "Eredar", slug: "eredar" },
  { label: "Eversong", slug: "eversong" },
  { label: "Executus", slug: "executus" },
  { label: "Exodar", slug: "exodar" },
  { label: "Festung der Stürme", slug: "festung-der-sturme" },
  { label: "Finkle", slug: "finkle" },
  { label: "Frostmane", slug: "frostmane" },
  { label: "Frostmourne", slug: "frostmourne" },
  { label: "Frostwhisper", slug: "frostwhisper" },
  { label: "Frostwolf", slug: "frostwolf" },
  { label: "Galakrond", slug: "galakrond" },
  { label: "Garona", slug: "garona" },
  { label: "Garrosh", slug: "garrosh" },
  { label: "Genjuros", slug: "genjuros" },
  { label: "Ghostlands", slug: "ghostlands" },
  { label: "Gilneas", slug: "gilneas" },
  { label: "Gordunni", slug: "gordunni" },
  { label: "Gorgonnash", slug: "gorgonnash" },
  { label: "Grizzly Hills", slug: "grizzly-hills" },
  { label: "Grim Batol", slug: "grim-batol" },
  { label: "Gul'dan", slug: "guldan" },
  { label: "Hakkar", slug: "hakkar" },
  { label: "Haomarush", slug: "haomarush" },
  { label: "Hellfire", slug: "hellfire" },
  { label: "Hellscream", slug: "hellscream" },
  { label: "Howling Fjord", slug: "howling-fjord" },
  { label: "Hyjal", slug: "hyjal" },
  { label: "Illidan", slug: "illidan" },
  { label: "Jaedenar", slug: "jaedenar" },
  { label: "Kael'thas", slug: "kaelthas" },
  { label: "Karazhan", slug: "karazhan" },
  { label: "Kazzak", slug: "kazzak" },
  { label: "Kel'Thuzad", slug: "kelthuzad" },
  { label: "Khadgar", slug: "khadgar" },
  { label: "Khaz Modan", slug: "khaz-modan" },
  { label: "Khaz'goroth", slug: "khazgoroth" },
  { label: "Kil'jaeden", slug: "kiljaeden" },
  { label: "Kilrogg", slug: "kilrogg" },
  { label: "Kirin Tor", slug: "kirin-tor" },
  { label: "Kor'gall", slug: "korgall" },
  { label: "Krasus", slug: "krasus" },
  { label: "Kul Tiras", slug: "kul-tiras" },
  { label: "Kult der Verdammten", slug: "kult-der-verdammten" },
  { label: "La Croisade écarlate", slug: "la-croisade-ecarlate" },
  { label: "Laughing Skull", slug: "laughing-skull" },
  { label: "Les Clairvoyants", slug: "les-clairvoyants" },
  { label: "Les Sentinelles", slug: "les-sentinelles" },
  { label: "Lightbringer", slug: "lightbringer" },
  { label: "Lightning's Blade", slug: "lightnings-blade" },
  { label: "Lordaeron", slug: "lordaeron" },
  { label: "Los Errantes", slug: "los-errantes" },
  { label: "Lothar", slug: "lothar" },
  { label: "Madmortem", slug: "madmortem" },
  { label: "Magtheridon", slug: "magtheridon" },
  { label: "Mal'Ganis", slug: "malganis" },
  { label: "Malfurion", slug: "malfurion" },
  { label: "Malorne", slug: "malorne" },
  { label: "Malygos", slug: "malygos" },
  { label: "Mannaroth", slug: "mannaroth" },
  { label: "Marécage de Zangar", slug: "marecage-de-zangar" },
  { label: "Mazrigos", slug: "mazrigos" },
  { label: "Medivh", slug: "medivh" },
  { label: "Minahonda", slug: "minahonda" },
  { label: "Mograine", slug: "mograine" },
  { label: "Moonglade", slug: "moonglade" },
  { label: "Moonrunner", slug: "moonrunner" },
  { label: "Nathrezim", slug: "nathrezim" },
  { label: "Naxxramas", slug: "naxxramas" },
  { label: "Nazjatar", slug: "nazjatar" },
  { label: "Nefarian", slug: "nefarian" },
  { label: "Nemesis", slug: "nemesis" },
  { label: "Nethersturm", slug: "nethersturm" },
  { label: "Nordrassil", slug: "nordrassil" },
  { label: "Norgannon", slug: "norgannon" },
  { label: "Nozdormu", slug: "nozdormu" },
  { label: "Onyxia", slug: "onyxia" },
  { label: "Outland", slug: "outland" },
  { label: "Perenolde", slug: "perenolde" },
  { label: "Piken Square", slug: "piken-square" },
  { label: "Pozzo dell'Eternità", slug: "pozzo-delleternita" },
  { label: "Proudmoore", slug: "proudmoore" },
  { label: "Quel'Thalas", slug: "quelthalas" },
  { label: "Ragnaros", slug: "ragnaros" },
  { label: "Rajaxx", slug: "rajaxx" },
  { label: "Rashgarroth", slug: "rashgarroth" },
  { label: "Ravencrest", slug: "ravencrest" },
  { label: "Ravenholdt", slug: "ravenholdt" },
  { label: "Rexxar", slug: "rexxar" },
  { label: "Runetotem", slug: "runetotem" },
  { label: "Sanguino", slug: "sanguino" },
  { label: "Sargeras", slug: "sargeras" },
  { label: "Saurfang", slug: "saurfang" },
  { label: "Scarshield Legion", slug: "scarshield-legion" },
  { label: "Sen'jin", slug: "senjin" },
  { label: "Shadowsong", slug: "shadowsong" },
  { label: "Shattered Halls", slug: "shattered-halls" },
  { label: "Shattered Hand", slug: "shattered-hand" },
  { label: "Shattrath", slug: "shattrath" },
  { label: "Silvermoon", slug: "silvermoon" },
  { label: "Sindragosa", slug: "sindragosa" },
  { label: "Skullcrusher", slug: "skullcrusher" },
  { label: "Soulflayer", slug: "soulflayer" },
  { label: "Spinebreaker", slug: "spinebreaker" },
  { label: "Sporeggar", slug: "sporeggar" },
  { label: "Steamwheedle Cartel", slug: "steamwheedle-cartel" },
  { label: "Stormrage", slug: "stormrage" },
  { label: "Stormreaver", slug: "stormreaver" },
  { label: "Stormscale", slug: "stormscale" },
  { label: "Sunstrider", slug: "sunstrider" },
  { label: "Sylvanas", slug: "sylvanas" },
  { label: "Taerar", slug: "taerar" },
  { label: "Talnivarr", slug: "talnivarr" },
  { label: "Tarren Mill", slug: "tarren-mill" },
  { label: "Teldrassil", slug: "teldrassil" },
  { label: "Temple noir", slug: "temple-noir" },
  { label: "Terenas", slug: "terenas" },
  { label: "Terrordar", slug: "terrordar" },
  { label: "The Maelstrom", slug: "the-maelstrom" },
  { label: "The Sha'tar", slug: "the-shatar" },
  { label: "The Venture Co", slug: "the-venture-co" },
  { label: "Theradras", slug: "theradras" },
  { label: "Thrall", slug: "thrall" },
  { label: "Thunderhorn", slug: "thunderhorn" },
  { label: "Tirion", slug: "tirion" },
  { label: "Todeswache", slug: "todeswache" },
  { label: "Tormented", slug: "tormented" },
  { label: "Trollbane", slug: "trollbane" },
  { label: "Turalyon", slug: "turalyon" },
  { label: "Twilight's Hammer", slug: "twilights-hammer" },
  { label: "Twisting Nether", slug: "twisting-nether" },
  { label: "Tyrande", slug: "tyrande" },
  { label: "Uldaman", slug: "uldaman" },
  { label: "Ulduar", slug: "ulduar" },
  { label: "Uldum", slug: "uldum" },
  { label: "Un'goro", slug: "ungoro" },
  { label: "Vashj", slug: "vashj" },
  { label: "Vek'nilash", slug: "veknilash" },
  { label: "Wildhammer", slug: "wildhammer" },
  { label: "Xavius", slug: "xavius" },
  { label: "Ysera", slug: "ysera" },
  { label: "Ysondre", slug: "ysondre" },
  { label: "Zenedar", slug: "zenedar" },
  { label: "Zul'jin", slug: "zuljin" },
];
