import { RealmOption } from "./euRealms.ts";

export const NA_REALMS: RealmOption[] = [
  { label: "Aegwynn", slug: "aegwynn" },
  { label: "Aerie Peak", slug: "aerie-peak" },
  { label: "Agamaggan", slug: "agamaggan" },
  { label: "Aggramar", slug: "aggramar" },
  { label: "Alexstrasza", slug: "alexstrasza" },
  { label: "Alleria", slug: "alleria" },
  { label: "Altar of Storms", slug: "altar-of-storms" },
  { label: "Alterac Mountains", slug: "alterac-mountains" },
  { label: "Andorhal", slug: "andorhal" },
  { label: "Anetheron", slug: "anetheron" },
  { label: "Antonidas", slug: "antonidas" },
  { label: "Anub'arak", slug: "anubarak" },
  { label: "Anvilmar", slug: "anvilmar" },
  { label: "Arathor", slug: "arathor" },
  { label: "Archimonde", slug: "archimonde" },
  { label: "Area 52", slug: "area-52" },
  { label: "Argent Dawn", slug: "argent-dawn" },
  { label: "Arthas", slug: "arthas" },
  { label: "Arygos", slug: "arygos" },
  { label: "Azgalor", slug: "azgalor" },
  { label: "Azjol-Nerub", slug: "azjol-nerub" },
  { label: "Azralon", slug: "azralon" },
  { label: "Azshara", slug: "azshara" },
  { label: "Azuremyst", slug: "azuremyst" },
  { label: "Baelgun", slug: "baelgun" },
  { label: "Balnazzar", slug: "balnazzar" },
  { label: "Barthilas", slug: "barthilas" },
  { label: "Blackhand", slug: "blackhand" },
  { label: "Blackrock", slug: "blackrock" },
  { label: "Blackwater Raiders", slug: "blackwater-raiders" },
  { label: "Blackwing Lair", slug: "blackwing-lair" },
  { label: "Blade's Edge", slug: "blades-edge" },
  { label: "Bladefist", slug: "bladefist" },
  { label: "Bleeding Hollow", slug: "bleeding-hollow" },
  { label: "Blood Furnace", slug: "blood-furnace" },
  { label: "Bloodhoof", slug: "bloodhoof" },
  { label: "Bloodscalp", slug: "bloodscalp" },
  { label: "Borean Tundra", slug: "borean-tundra" },
  { label: "Boulderfist", slug: "boulderfist" },
  { label: "Bronzebeard", slug: "bronzebeard" },
  { label: "Burning Blade", slug: "burning-blade" },
  { label: "Burning Legion", slug: "burning-legion" },
  { label: "Caelestrasz", slug: "caelestrasz" },
  { label: "Cairne", slug: "cairne" },
  { label: "Cenarion Circle", slug: "cenarion-circle" },
  { label: "Cenarion Expedition", slug: "cenarion-expedition" },
  { label: "Cho'gall", slug: "chogall" },
  { label: "Chromaggus", slug: "chromaggus" },
  { label: "Crushridge", slug: "crushridge" },
  { label: "Daggerspine", slug: "daggerspine" },
  { label: "Dalaran", slug: "dalaran" },
  { label: "Dalvengyr", slug: "dalvengyr" },
  { label: "Dark Iron", slug: "dark-iron" },
  { label: "Darkspear", slug: "darkspear" },
  { label: "Darrowmere", slug: "darrowmere" },
  { label: "Dath'Remar", slug: "dathremar" },
  { label: "Dawnbringer", slug: "dawnbringer" },
  { label: "Deathwing", slug: "deathwing" },
  { label: "Dentarg", slug: "dentarg" },
  { label: "Destromath", slug: "destromath" },
  { label: "Dethecus", slug: "dethecus" },
  { label: "Detheroc", slug: "detheroc" },
  { label: "Doomhammer", slug: "doomhammer" },
  { label: "Draenor", slug: "draenor" },
  { label: "Dragonblight", slug: "dragonblight" },
  { label: "Dragonmaw", slug: "dragonmaw" },
  { label: "Draka", slug: "draka" },
  { label: "Drakkari", slug: "drakkari" },
  { label: "Drak'Tharon", slug: "draktharon" },
  { label: "Drak'thul", slug: "drakthul" },
  { label: "Dreadmaul", slug: "dreadmaul" },
  { label: "Dunemaul", slug: "dunemaul" },
  { label: "Durotan", slug: "durotan" },
  { label: "Duskwood", slug: "duskwood" },
  { label: "Earthen Ring", slug: "earthen-ring" },
  { label: "Echo Isles", slug: "echo-isles" },
  { label: "Eitrigg", slug: "eitrigg" },
  { label: "Eldre'Thalas", slug: "eldrethalas" },
  { label: "Elune", slug: "elune" },
  { label: "Emerald Dream", slug: "emerald-dream" },
  { label: "Eonar", slug: "eonar" },
  { label: "Eredar", slug: "eredar" },
  { label: "Executus", slug: "executus" },
  { label: "Exodar", slug: "exodar" },
  { label: "Farstriders", slug: "farstriders" },
  { label: "Feathermoon", slug: "feathermoon" },
  { label: "Fenris", slug: "fenris" },
  { label: "Firetree", slug: "firetree" },
  { label: "Fizzcrank", slug: "fizzcrank" },
  { label: "Frostmane", slug: "frostmane" },
  { label: "Frostmourne", slug: "frostmourne" },
  { label: "Frostwolf", slug: "frostwolf" },
  { label: "Fugitive Vale", slug: "fugitive-vale" },
  { label: "Galakrond", slug: "galakrond" },
  { label: "Gallywix", slug: "gallywix" },
  { label: "Garona", slug: "garona" },
  { label: "Garrosh", slug: "garrosh" },
  { label: "Ghostlands", slug: "ghostlands" },
  { label: "Gilneas", slug: "gilneas" },
  { label: "Gnomeregan", slug: "gnomeregan" },
  { label: "Goldrinn", slug: "goldrinn" },
  { label: "Greymane", slug: "greymane" },
  { label: "Grizzly Hills", slug: "grizzly-hills" },
  { label: "Gul'dan", slug: "guldan" },
  { label: "Gurubashi", slug: "gurubashi" },
  { label: "Hakkar", slug: "hakkar" },
  { label: "Haomarush", slug: "haomarush" },
  { label: "Hellscream", slug: "hellscream" },
  { label: "Hydraxis", slug: "hydraxis" },
  { label: "Icecrown", slug: "icecrown" },
  { label: "Illidan", slug: "illidan" },
  { label: "Jaedenar", slug: "jaedenar" },
  { label: "Jubei'Thos", slug: "jubeithos" },
  { label: "Kalecgos", slug: "kalecgos" },
  { label: "Kargath", slug: "kargath" },
  { label: "Kel'Thuzad", slug: "kelthuzad" },
  { label: "Khadgar", slug: "khadgar" },
  { label: "Khaz Modan", slug: "khaz-modan" },
  { label: "Khaz'goroth", slug: "khazgoroth" },
  { label: "Kil'jaeden", slug: "kiljaeden" },
  { label: "Kilrogg", slug: "kilrogg" },
  { label: "Kirin Tor", slug: "kirin-tor" },
  { label: "Korgath", slug: "korgath" },
  { label: "Kul Tiras", slug: "kul-tiras" },
  { label: "Laughing Skull", slug: "laughing-skull" },
  { label: "Lethon", slug: "lethon" },
  { label: "Lightbringer", slug: "lightbringer" },
  { label: "Lightning's Blade", slug: "lightnings-blade" },
  { label: "Llane", slug: "llane" },
  { label: "Lothar", slug: "lothar" },
  { label: "Madoran", slug: "madoran" },
  { label: "Maelstrom", slug: "maelstrom" },
  { label: "Magtheridon", slug: "magtheridon" },
  { label: "Mal'Ganis", slug: "malganis" },
  { label: "Malfurion", slug: "malfurion" },
  { label: "Malorne", slug: "malorne" },
  { label: "Malygos", slug: "malygos" },
  { label: "Mannoroth", slug: "mannoroth" },
  { label: "Medivh", slug: "medivh" },
  { label: "Moonrunner", slug: "moonrunner" },
  { label: "Mug'thol", slug: "mugthol" },
  { label: "Muradin", slug: "muradin" },
  { label: "Nagrand", slug: "nagrand" },
  { label: "Nathrezim", slug: "nathrezim" },
  { label: "Nazgrel", slug: "nazgrel" },
  { label: "Nazjatar", slug: "nazjatar" },
  { label: "Ner'zhul", slug: "nerzhul" },
  { label: "Norgannon", slug: "norgannon" },
  { label: "Onyxia", slug: "onyxia" },
  { label: "Perenolde", slug: "perenolde" },
  { label: "Proudmoore", slug: "proudmoore" },
  { label: "Quel'Thalas", slug: "quelthalas" },
  { label: "Ragnaros", slug: "ragnaros" },
  { label: "Ravencrest", slug: "ravencrest" },
  { label: "Ravenholdt", slug: "ravenholdt" },
  { label: "Rexxar", slug: "rexxar" },
  { label: "Rivendare", slug: "rivendare" },
  { label: "Runetotem", slug: "runetotem" },
  { label: "Sargeras", slug: "sargeras" },
  { label: "Saurfang", slug: "saurfang" },
  { label: "Scarlet Crusade", slug: "scarlet-crusade" },
  { label: "Sen'jin", slug: "senjin" },
  { label: "Sentinels", slug: "sentinels" },
  { label: "Shadow Council", slug: "shadow-council" },
  { label: "Shadowmoon", slug: "shadowmoon" },
  { label: "Shadowsong", slug: "shadowsong" },
  { label: "Shattered Halls", slug: "shattered-halls" },
  { label: "Shattered Hand", slug: "shattered-hand" },
  { label: "Silver Hand", slug: "silver-hand" },
  { label: "Silvermoon", slug: "silvermoon" },
  { label: "Sisters of Elune", slug: "sisters-of-elune" },
  { label: "Skullcrusher", slug: "skullcrusher" },
  { label: "Skywall", slug: "skywall" },
  { label: "Smolderthorn", slug: "smolderthorn" },
  { label: "Spinebreaker", slug: "spinebreaker" },
  { label: "Spirestone", slug: "spirestone" },
  { label: "Staghelm", slug: "staghelm" },
  { label: "Stormrage", slug: "stormrage" },
  { label: "Stormreaver", slug: "stormreaver" },
  { label: "Stormscale", slug: "stormscale" },
  { label: "Suramar", slug: "suramar" },
  { label: "Tanaris", slug: "tanaris" },
  { label: "Terenas", slug: "terenas" },
  { label: "Terokkar", slug: "terokkar" },
  { label: "Thaurissan", slug: "thaurissan" },
  { label: "The Forgotten Coast", slug: "the-forgotten-coast" },
  { label: "The Scryers", slug: "the-scryers" },
  { label: "The Underbog", slug: "the-underbog" },
  { label: "Thorium Brotherhood", slug: "thorium-brotherhood" },
  { label: "Thrall", slug: "thrall" },
  { label: "Thunderhorn", slug: "thunderhorn" },
  { label: "Thunderlord", slug: "thunderlord" },
  { label: "Tichondrius", slug: "tichondrius" },
  { label: "Tormentis", slug: "tormentis" },
  { label: "Trollbane", slug: "trollbane" },
  { label: "Turalyon", slug: "turalyon" },
  { label: "Twisting Nether", slug: "twisting-nether" },
  { label: "Uldaman", slug: "uldaman" },
  { label: "Uldum", slug: "uldum" },
  { label: "Undermine", slug: "undermine" },
  { label: "Ursin", slug: "ursin" },
  { label: "Uther", slug: "uther" },
  { label: "Vashj", slug: "vashj" },
  { label: "Vek'nilash", slug: "veknilash" },
  { label: "Velen", slug: "velen" },
  { label: "Warsong", slug: "warsong" },
  { label: "Whisperwind", slug: "whisperwind" },
  { label: "Wildhammer", slug: "wildhammer" },
  { label: "Windrunner", slug: "windrunner" },
  { label: "Winterhoof", slug: "winterhoof" },
  { label: "Wyrmrest Accord", slug: "wyrmrest-accord" },
  { label: "Ysera", slug: "ysera" },
  { label: "Ysondre", slug: "ysondre" },
  { label: "Zangarmarsh", slug: "zangarmarsh" },
  { label: "Zuluhed", slug: "zuluhed" },
];
